/*
Generated by: DeepSeek-V3
Prompt:
"""
Создай оптимизированную SQL функцию для выборки 3000 заказов из 50000 с средним количеством элементов 3 на заказ. Время выполнения должно быть 1-2 секунды. Используй:
1. JOIN вместо скалярных функций
2. NOT EXISTS вместо NOT IN
3. Дополнительные индексы
4. Другие оптимизации на твой выбор
Не изменяй структуру БД.
"""
*/

CREATE INDEX IX_Works_IdWork_Del ON Works(Id_Work) WHERE IS_DEL <> 1
CREATE INDEX IX_WorkItem_WorkAnaliz ON WorkItem(Id_Work, is_complit, ID_ANALIZ)
CREATE INDEX IX_Analiz_Group ON Analiz(ID_ANALIZ) WHERE is_group = 1

CREATE OR ALTER FUNCTION [dbo].[F_WORKS_LIST_OPTIMIZED]()
RETURNS TABLE
AS
RETURN (
    SELECT
        w.Id_Work,
        w.CREATE_Date,
        w.MaterialNumber,
        w.IS_Complit,
        w.FIO,
        CONVERT(VARCHAR(10), w.CREATE_Date, 104) AS D_DATE,
        (
            SELECT COUNT(*)
            FROM WorkItem wi WITH (NOLOCK)
            WHERE wi.Id_Work = w.Id_Work
            AND wi.is_complit = 0
            AND NOT EXISTS (
                SELECT 1
                FROM Analiz a WITH (NOLOCK)
                WHERE a.ID_ANALIZ = wi.ID_ANALIZ
                AND a.is_group = 1
            )
        ) AS WorkItemsNotComplit,
        (
            SELECT COUNT(*)
            FROM WorkItem wi WITH (NOLOCK)
            WHERE wi.Id_Work = w.Id_Work
            AND wi.is_complit = 1
            AND NOT EXISTS (
                SELECT 1
                FROM Analiz a WITH (NOLOCK)
                WHERE a.ID_ANALIZ = wi.ID_ANALIZ
                AND a.is_group = 1
            )
        ) AS WorkItemsComplit,
        ISNULL(e.SURNAME, '') + ' ' +
        ISNULL(LEFT(e.NAME, 1), '') + '. ' +
        ISNULL(LEFT(e.PATRONYMIC, 1), '') + '.' AS FULL_NAME,
        w.StatusId,
        ws.StatusName,
        CASE WHEN w.Print_Date IS NOT NULL OR
                  w.SendToClientDate IS NOT NULL OR
                  w.SendToDoctorDate IS NOT NULL OR
                  w.SendToOrgDate IS NOT NULL OR
                  w.SendToFax IS NOT NULL
             THEN 1 ELSE 0 END AS Is_Print
    FROM Works w WITH (NOLOCK)
    LEFT JOIN WorkStatus ws WITH (NOLOCK) ON w.StatusId = ws.StatusID
    LEFT JOIN Employee e WITH (NOLOCK) ON w.Id_Employee = e.Id_Employee
    WHERE w.IS_DEL <> 1
)
